/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integratedframework;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author pooja
 */
public class SearchWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchWindow
     */
    String query;
    DefaultListModel model = new DefaultListModel();
        
    public SearchWindow() {
        initComponents();
        query="";
        model.addElement("cloud");
        model.addElement("iot");
        model.addElement("hadoop");
        pk.setModel(model);
//         try
//                         {
//                         String username="root";
//                         String password="";
//                         String url1="jdbc:mysql://localhost/crawl";
//                         Class.forName("com.mysql.jdbc.Driver").newInstance();
//                         java.sql.Connection con=DriverManager.getConnection(url1,username,password);
//                        
//                         java.sql.PreparedStatement ps=con.prepareStatement("insert into ");
//                         }
//             catch(Exception ee)
//             {
//               System.out.println(ee);
//             }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qry = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rst = new javax.swing.JButton();
        cnf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pk = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(qry);
        qry.setBounds(160, 50, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Predefined Knowledge");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 110, 140, 30);

        rst.setText("Reset");
        rst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstActionPerformed(evt);
            }
        });
        getContentPane().add(rst);
        rst.setBounds(460, 50, 80, 23);

        cnf.setText("Confirm");
        cnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfActionPerformed(evt);
            }
        });
        getContentPane().add(cnf);
        cnf.setBounds(350, 50, 80, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your Query");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 140, 40);

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 210, 90, 23);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 160, 90, 23);

        pk.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "data", "hadoop", "IOT", "cloud" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(pk);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 160, 140, 130);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 0, 2);

        jButton3.setText("Visualization");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 230, 130, 23);

        jButton4.setText("Crawling");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 140, 130, 23);

        jButton5.setText("Analysis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(40, 180, 130, 23);

        jButton6.setText("view result");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(230, 140, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integratedframework/images/integrated.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 790, 360);

        jMenu1.setText("File");

        jMenuItem1.setText("Clear Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 812, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void cnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfActionPerformed
        // TODO add your handling code here:
        query=qry.getText();
    }//GEN-LAST:event_cnfActionPerformed

    private void rstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstActionPerformed
        // TODO add your handling code here:
        qry.setText("");
        query="";
    }//GEN-LAST:event_rstActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String item=JOptionPane.showInputDialog("enter item to add");
        int pos=model.getSize();
        model.add(pos,item);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(model.size()>0)
        {
        String item=pk.getSelectedValue();
        int index=model.indexOf(item);
        model.remove(index);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"no items to remove");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
                         {
                         String username="root";
                         String password="";
                         String url1="jdbc:mysql://localhost/crawl";
                         Class.forName("com.mysql.jdbc.Driver").newInstance();
                         java.sql.Connection con=DriverManager.getConnection(url1,username,password);
                         Statement st=con.createStatement();
                         ResultSet rs=st.executeQuery("select distinct sum(no) from data");
                         rs=st.executeQuery("select distinct value,no from data order by no ASC");
                         FileOutputStream fout=new FileOutputStream("final.txt");
                         PrintStream ps=new PrintStream(fout);
                         while(rs.next())
                         {
                            ps.println(rs.getString(2)+" "+rs.getString(1));
                         }
                         ps.close();
                         st.close();
                         String args[]=new String[1];
                         BarChartExample example=new BarChartExample("Bar Chart Window");  
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);
                         
                         }
             catch(Exception ee)
             {
               System.out.println(ee);
             }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(query.length()>0)
        {
            String args[]=new String[1];
            args[0]=query;
            DoSearch.main(args);
             CrawlingResult cc=new CrawlingResult();
             cc.setVisible(true);
        }
        else
        {
          JOptionPane.showMessageDialog(this,"no confirmed query");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try
        {
     Spider sp=new Spider();
     FileInputStream fin=new FileInputStream("result.txt");
     DataInputStream din=new DataInputStream(fin);
     String sg=din.readLine();
     while(sg!=null)
        {
         if(sg.startsWith("www."))
         {
           //System.out.println(sg);
           sg=sg.substring(4);
           //System.out.println(sg);
           sg="http://"+sg+"/";
         for(int i=0;i<model.size();i++)
         {
           
           
           String tag=(String) model.elementAt(i);
           System.out.println(sg+" "+tag);
           try
           {
           sp.search(sg,tag);          
           }catch(Exception ee)
           {
               i++;
           }
         }
         }
         L1: sg=din.readLine();
        }
        }
        catch(Exception ee)
        {
          System.out.println("manoj:" +ee);
          
        }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        CrawlingResult ss=new CrawlingResult();
        ss.setVisible(true);
        //this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        
        
         try {
            String userName = "root";
            String password = "";
            String url="jdbc:mysql://localhost:3306/crawl";
           // String url = "jdbc:mysql://localhost/sspais";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url, userName, password);
            Statement st = con.createStatement();
            String sql= "truncate table data";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "successfully cleared...");
         }catch(Exception e){
             System.out.println(e);
         }
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cnf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> pk;
    private javax.swing.JTextField qry;
    private javax.swing.JButton rst;
    // End of variables declaration//GEN-END:variables
}
