/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integratedframework;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pooja
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
        this.setBounds(100, 100, 450, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPasswordField2.setText("jPasswordField2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integratedframework/images/nostalgic_blue_background_03_hd_picture_169784.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        getContentPane().setLayout(null);

        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 74, 90, 30);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 160, 90, 14);
        getContentPane().add(username1);
        username1.setBounds(180, 80, 150, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 230, 120, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 80, 150, 30);

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });
        getContentPane().add(password1);
        password1.setBounds(181, 160, 150, 30);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/integratedframework/images/nostalgic_blue_background_03_hd_picture_169784.jpg"))); // NOI18N
        jLabel6.setText("Login Page");
        jPanel1.add(jLabel6);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 470, 400);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 440, 260);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(24, 20, 140, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
     /*   SearchWindow s=new SearchWindow();
        s.setVisible(true);
        this.dispose();*/
        
  /*  String m=username1.getText();
        String n= new String(password1.getPassword());
try{      
     
    String username="root";
       String password="";
       String url="jdbc:mysql://localhost/crawl";
      
       
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url, username, password);
           
             Statement st= con.createStatement();
  
    
        
           String q="select * from user where username='"+m+"'";
           ResultSet rs=st.executeQuery(q);
           rs.next();
           String username1, password1;
           username1 =rs.getString("username");
           password1 =rs.getString("password");
           { if(m.compareTo(username1)==0)
                 if(n.compareTo(password1)==0)
                    System.out.println("login Success");
                 else
                     System.out.println("Wrong Password");
           
           }
      }catch(Exception ex){
           System.out.println(ex);
       }
   */

  
 
        //read values from user table in sql database    
         
    
         
         String m=username1.getText();
        String n= new String(password1.getPassword());
try{      
     
    String username="root";
       String password="";
       String url="jdbc:mysql://localhost/crawl";
      
       
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url, username, password);
           
             Statement st= con.createStatement();
  
    
        
           String q="select * from user where username='"+m+"'";
           ResultSet rs=st.executeQuery(q);
           rs.next();
           String username1, password1;
           username1 =rs.getString("username");
           password1 =rs.getString("password");
           { if(m.compareTo(username1)==0)
                 if(n.compareTo(password1)==0)
                 {
                      JOptionPane.showMessageDialog(this,"login successful");
               SearchWindow s=new SearchWindow();
        s.setVisible(true);
        this.dispose();
                }
        else
                     //System.out.println("Wrong Password");
           
                     JOptionPane.showMessageDialog(this,"wrong username or password");
           }
      }catch(Exception ex){
           System.out.println(ex);
       }
   

  

        //read values from user table in sql database    
         
        
   

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
